/**
 * Data access layer for the Invitations module.
 *
 * This is a DUMB in-memory data layer: it performs no email validation,
 * no expiry business rules, and no token generation. Those concerns
 * belong to the service layer. Query helpers that filter on `expires_at`
 * / `redeemed_at` (e.g. findPendingByEmail, findPendingByUser, listPending)
 * are considered query concerns and are implemented here for convenience.
 *
 * Lookup methods that can fail to find a record return `null` (never
 * `undefined`, never a thrown error) so callers can rely on a single
 * "not found" sentinel.
 */

import { Invitation } from './types';

/**
 * A registered user. Kept local to the repository layer (not part of the
 * shared invitations contract in ./types) so that types.ts remains
 * untouched by this layer.
 */
export interface User {
  id: string;
  email: string;
  name: string;
  password_hash: string;
  created_at: string;
}

export type CreateUserInput = Omit<User, 'id' | 'created_at'> & {
  id?: string;
  created_at?: string;
};

export type CreateInvitationInput = Invitation;

/**
 * Simple id generator. This is a data-layer implementation detail only
 * (not the invitation token itself, which is generated by the service).
 */
function generateId(prefix: string): string {
  return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 10)}`;
}

/**
 * Canonical key for email indexes. Email local parts are technically
 * case-sensitive per RFC 5321, but no real provider treats them that way,
 * and treating "Alice@example.com" as distinct from "alice@example.com"
 * would let a caller bypass the duplicate-invitation and
 * already-registered checks just by changing case. Indexes are keyed on
 * this form; stored records keep the original casing the caller supplied,
 * the same way a case-insensitive database index behaves.
 */
function emailKey(email: string): string {
  return email.trim().toLowerCase();
}

export class InvitationRepository {
  private byId: Map<string, Invitation> = new Map();
  private tokenIndex: Map<string, string> = new Map(); // token -> id
  private emailIndex: Map<string, Set<string>> = new Map(); // email -> Set<id>

  /**
   * Create a new invitation record. Throws if the token is already in use.
   */
  create(data: CreateInvitationInput): Invitation {
    if (this.tokenIndex.has(data.token)) {
      throw new Error(`Invitation with token already exists`);
    }
    if (this.byId.has(data.id)) {
      throw new Error(`Invitation with id "${data.id}" already exists`);
    }

    const invitation: Invitation = { ...data };

    this.byId.set(invitation.id, invitation);
    this.tokenIndex.set(invitation.token, invitation.id);

    const key = emailKey(invitation.email);
    const emailSet = this.emailIndex.get(key) ?? new Set<string>();
    emailSet.add(invitation.id);
    this.emailIndex.set(key, emailSet);

    return { ...invitation };
  }

  findById(id: string): Invitation | null {
    const invitation = this.byId.get(id);
    return invitation ? { ...invitation } : null;
  }

  findByToken(token: string): Invitation | null {
    const id = this.tokenIndex.get(token);
    if (!id) return null;
    return this.findById(id);
  }

  findByEmail(email: string): Invitation[] {
    const ids = this.emailIndex.get(emailKey(email));
    if (!ids) return [];
    return Array.from(ids)
      .map((id) => this.byId.get(id))
      .filter((inv): inv is Invitation => Boolean(inv))
      .map((inv) => ({ ...inv }));
  }

  /**
   * Returns the first pending (not redeemed, not expired) invitation for
   * an email, or null if none exists.
   */
  findPendingByEmail(email: string, now: Date = new Date()): Invitation | null {
    const nowIso = now.toISOString();
    const pending = this.findByEmail(email).find(
      (inv) => !inv.redeemed_at && inv.expires_at > nowIso
    );
    return pending ?? null;
  }

  /**
   * Returns all pending (not redeemed, not expired) invitations created
   * by a given user. Used to enforce the "max N pending invites per user"
   * rate-limit rule in the service layer.
   */
  findPendingByUser(userId: string, now: Date = new Date()): Invitation[] {
    const nowIso = now.toISOString();
    return this.list().filter(
      (inv) =>
        inv.created_by_user_id === userId &&
        !inv.redeemed_at &&
        inv.expires_at > nowIso
    );
  }

  /**
   * Marks an invitation as redeemed. Returns the updated invitation, or
   * null if no invitation exists for the given token.
   */
  markRedeemed(token: string, redeemedByUserId: string, redeemedAt: string = new Date().toISOString()): Invitation | null {
    const id = this.tokenIndex.get(token);
    if (!id) return null;

    const invitation = this.byId.get(id);
    if (!invitation) return null;

    const updated: Invitation = {
      ...invitation,
      redeemed_at: redeemedAt,
      redeemed_by_user_id: redeemedByUserId,
    };
    this.byId.set(id, updated);
    return { ...updated };
  }

  /**
   * Applies a partial update to an invitation. Returns the updated
   * invitation, or null if no invitation exists for the given id.
   * Attempts to change `id` or `token` to a value already used by
   * another record will throw.
   */
  update(id: string, patch: Partial<Invitation>): Invitation | null {
    const existing = this.byId.get(id);
    if (!existing) return null;

    if (patch.token && patch.token !== existing.token && this.tokenIndex.has(patch.token)) {
      throw new Error(`Invitation with token already exists`);
    }

    const updated: Invitation = { ...existing, ...patch, id: existing.id };

    // Keep the token index in sync if the token changed.
    if (patch.token && patch.token !== existing.token) {
      this.tokenIndex.delete(existing.token);
      this.tokenIndex.set(updated.token, id);
    }

    // Keep the email index in sync if the email changed.
    if (patch.email && emailKey(patch.email) !== emailKey(existing.email)) {
      this.emailIndex.get(emailKey(existing.email))?.delete(id);
      const newKey = emailKey(updated.email);
      const newSet = this.emailIndex.get(newKey) ?? new Set<string>();
      newSet.add(id);
      this.emailIndex.set(newKey, newSet);
    }

    this.byId.set(id, updated);
    return { ...updated };
  }

  /**
   * Deletes an invitation by id. Returns true if a record was deleted,
   * false if no record existed for the id.
   */
  delete(id: string): boolean {
    const existing = this.byId.get(id);
    if (!existing) return false;

    this.byId.delete(id);
    this.tokenIndex.delete(existing.token);
    this.emailIndex.get(emailKey(existing.email))?.delete(id);

    return true;
  }

  list(): Invitation[] {
    return Array.from(this.byId.values()).map((inv) => ({ ...inv }));
  }

  listPending(now: Date = new Date()): Invitation[] {
    const nowIso = now.toISOString();
    return this.list().filter((inv) => !inv.redeemed_at && inv.expires_at > nowIso);
  }

  /** Test helper: resets all stored state. */
  clear(): void {
    this.byId.clear();
    this.tokenIndex.clear();
    this.emailIndex.clear();
  }
}

export class UserRepository {
  private byId: Map<string, User> = new Map();
  private emailIndex: Map<string, string> = new Map(); // email -> id

  /**
   * Creates a new user. Throws if the email is already registered.
   */
  create(data: CreateUserInput): User {
    if (this.emailIndex.has(emailKey(data.email))) {
      throw new Error(`User with email already exists`);
    }

    const user: User = {
      id: data.id ?? generateId('user'),
      email: data.email,
      name: data.name,
      password_hash: data.password_hash,
      created_at: data.created_at ?? new Date().toISOString(),
    };

    if (this.byId.has(user.id)) {
      throw new Error(`User with id "${user.id}" already exists`);
    }

    this.byId.set(user.id, user);
    this.emailIndex.set(emailKey(user.email), user.id);

    return { ...user };
  }

  findByEmail(email: string): User | null {
    const id = this.emailIndex.get(emailKey(email));
    if (!id) return null;
    return this.findById(id);
  }

  findById(id: string): User | null {
    const user = this.byId.get(id);
    return user ? { ...user } : null;
  }

  /** Test helper: resets all stored state. */
  clear(): void {
    this.byId.clear();
    this.emailIndex.clear();
  }
}

export const invitationRepository = new InvitationRepository();
export const userRepository = new UserRepository();
