#!/usr/bin/env bash
# ralph.sh — Autonomous AI agent loop
# Adapted from https://github.com/snarktank/ralph
#
# This script spawns fresh AI instances in a loop. Each instance:
#   1. Reads prd.json to find the next incomplete user story
#   2. Implements and tests that story
#   3. Updates prd.json (marks passes: true) and progress.txt
#   4. Commits to git
#   5. Exits — the next iteration starts with a clean context
#
# Usage: ./scripts/ralph/ralph.sh --tool claude
#        ./scripts/ralph/ralph.sh --tool claude --max-iterations 10

set -euo pipefail

# --- Configuration ---
TOOL="claude"
MAX_ITERATIONS=25
PRD_FILE="prd.json"
PROGRESS_FILE="progress.txt"
PROMPT_FILE="CLAUDE.md"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --tool) TOOL="$2"; shift 2 ;;
    --max-iterations) MAX_ITERATIONS="$2"; shift 2 ;;
    --prd) PRD_FILE="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# --- Helper functions ---

# Count how many stories still have "passes": false
remaining_stories() {
  python3 -c "
import json, sys
with open('$PRD_FILE') as f:
    prd = json.load(f)
stories = prd.get('stories', [])
remaining = [s for s in stories if not s.get('passes', False)]
print(len(remaining))
"
}

# Get the title of the next incomplete story
next_story_title() {
  python3 -c "
import json
with open('$PRD_FILE') as f:
    prd = json.load(f)
stories = prd.get('stories', [])
for s in stories:
    if not s.get('passes', False):
        print(s.get('title', 'Unknown'))
        break
"
}

# Check if all stories pass
all_done() {
  local remaining
  remaining=$(remaining_stories)
  [[ "$remaining" -eq 0 ]]
}

# --- Main loop ---

echo "=== Ralph Autonomous Agent Loop ==="
echo "Tool: $TOOL"
echo "PRD: $PRD_FILE"
echo "Max iterations: $MAX_ITERATIONS"
echo ""

# Ensure required files exist
if [[ ! -f "$PRD_FILE" ]]; then
  echo "Error: $PRD_FILE not found. Create it from your PRD first."
  exit 1
fi

if [[ ! -f "$PROMPT_FILE" ]]; then
  echo "Error: $PROMPT_FILE not found. Create a prompt template first."
  exit 1
fi

# Initialize progress file if it doesn't exist
if [[ ! -f "$PROGRESS_FILE" ]]; then
  echo "# Progress Log" > "$PROGRESS_FILE"
  echo "# Auto-generated by ralph.sh" >> "$PROGRESS_FILE"
  echo "" >> "$PROGRESS_FILE"
fi

iteration=0

while true; do
  iteration=$((iteration + 1))

  # Check if we're done
  if all_done; then
    echo ""
    echo "=== ALL STORIES PASSING ==="
    echo "Completed in $((iteration - 1)) iteration(s)."
    echo ""
    echo "Final prd.json:"
    cat "$PRD_FILE"
    exit 0
  fi

  # Check iteration limit
  if [[ "$iteration" -gt "$MAX_ITERATIONS" ]]; then
    echo ""
    echo "=== MAX ITERATIONS REACHED ($MAX_ITERATIONS) ==="
    echo "Remaining stories: $(remaining_stories)"
    echo "Check progress.txt for details."
    exit 1
  fi

  # Get current story info
  story=$(next_story_title)
  remaining=$(remaining_stories)

  echo "--- Iteration $iteration / $MAX_ITERATIONS ---"
  echo "Next story: $story"
  echo "Remaining: $remaining stories"
  echo ""

  # Log iteration start
  echo "## Iteration $iteration" >> "$PROGRESS_FILE"
  echo "- Started: $(date -Iseconds)" >> "$PROGRESS_FILE"
  echo "- Story: $story" >> "$PROGRESS_FILE"

  # Build the prompt for this iteration
  # The AI reads CLAUDE.md, prd.json, and progress.txt to understand context
  PROMPT=$(cat <<EOF
You are an autonomous coding agent running as iteration $iteration of the Ralph loop.

Read the following files to understand your task:
- CLAUDE.md — your prompt template with instructions
- prd.json — the product requirements with user stories (implement the next one where "passes" is false)
- progress.txt — learnings from previous iterations

Your workflow:
1. Read prd.json to find the next story where "passes" is false
2. Implement the code changes needed for that story
3. Run \`npm test\` to verify
4. If tests pass, update prd.json to mark the story as "passes": true
5. Append your learnings to progress.txt
6. Commit your changes to git

Do NOT stop until the current story's tests pass.
After completing, exit so the next iteration can start fresh.
EOF
)

  # Spawn a fresh AI instance
  # Each instance gets a clean context window — this is the key insight
  if [[ "$TOOL" == "claude" ]]; then
    echo "$PROMPT" | claude --print 2>&1 || true
  else
    echo "Unsupported tool: $TOOL"
    exit 1
  fi

  # Log iteration end
  echo "- Finished: $(date -Iseconds)" >> "$PROGRESS_FILE"
  echo "" >> "$PROGRESS_FILE"

  # Small delay between iterations
  sleep 2
done
